### ISSUE TITLE
Custom Fields Required Option doesn't actually work at all

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#103]
When you set the option to required it is just ignored.

**Comment by rdiaztushman** [comment]
Confirmed.  I noticed this while testing the datetime issue

**Comment by rdiaztushman** [comment]
This isn't a bug in Tienda, it was an issue in the Library's Dsc.formValidation() javascript function.  Dsc.formValidation() would only perform validation if the task was save/apply/save-as.  This is stupid.  So I changed the library javascript.  Setting something to required works fine.
