### ISSUE TITLE
[Already registered? Please click here to login] Link broken in one page checkout

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#104]
IF you are at the checkout page of one page checkout and you click the link that you are already registerd it takes you to a  login for, when you try to login you get redirected to a 404 pages

An error has occurred.
The requested page cannot be found.

and it doesn't log you in

the login URL is 
http://projects.ammonitenetworks.com/tienda/index.php/component/tienda/index.php?option=com_tienda&view=checkout&task=registrationLink&tmpl=component&return=aHR0cDovL3Byb2plY3RzLmFtbW9uaXRlbmV0d29ya3MuY29tL3RpZW5kYS9pbmRleC5waHAvY29tcG9uZW50L3RpZW5kYS9jaGVja291dD9JdGVtaWQ9MA==

DEBUG SHOWS THIS

Call stack
# Function    Location

1   JSite->dispatch()   /var/projects/tienda/index.php:42
2   JComponentHelper::renderComponent() /var/projects/tienda/includes/application.php:197
3   JError::raiseError()    /var/projects/tienda/libraries/joomla/application/component/helper.php:337
4   JError::raise() /var/projects/tienda/libraries/joomla/error/error.php:251

**Comment by rdiaztushman** [comment]
Disable SEF in the Joomla installation, then try again.  This may have something to do with the URL...

**Comment by ChrisFrench** [comment]
nope it is another login for that  needs to be adjusted because of the difference between com_user, and com_users....

**Comment by ChrisFrench** [comment]
I am fixing  it now

**Comment by ChrisFrench** [comment]
22dd6de1c68b0204b89153179e04c390dc75fdad
