### ISSUE TITLE
Errors in DSCTable for Config pages

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#108]
Rafael I found a bug  I wanted to ask your opinion on best way to fix. 

in DSCTable we have this code

function save($src='', $orderingFilter = '', $ignore = '')
    {...
        $app = $this->get('_app');

```
    if ( empty($app) || DSC::getApp( $app )->get('enable_reorder_table', '1') )
    {

        $this->reorder();
    }

    ...
}
```

This Creates an error on every load that says

TiendaTableConfig does not support ordering.

This also probably  effects our other apps, 

One solution is to put a save function in all of the  config table files that doesn't have the reorder snippet,  I was wondering if you have an idea of how to fix this right in the library that is  maybe better than editing all the configtable files?

**Comment by rdiaztushman** [comment]
We should update the ->reorder() function to first check the columns in the table before attempting the reorder.

**Comment by ChrisFrench** [comment]
Yea OK we can probably close this add it to the library project and assign it to me

**Comment by rdiaztushman** [comment]
Refs https://github.com/dioscouri/library/issues/14
