### ISSUE TITLE
Super dumb language thing  in coupon default page in admin 

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#109]
<?php echo JText::_('COUPON VALUE TYPE $item->coupon_value_type'); ?>

I am guessing this needs to be language  string that actually makes sense and is valid PHP

**Comment by rdiaztushman** [comment]
I committed a fix for this already, so be sure to go a git pull.

**Comment by ChrisFrench** [comment]
Opps I missed this and got a annoying conflict because we both fixed the same thing haha my bad
