### ISSUE TITLE
Coupons don't use OrderItems tables to store discount in field, just in total which seems wrong

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#112]
the coupon system  should add and save the discounts into the order table I think. 
Right now we have this  unfield in the OrderItems table that doesn't  get used at all. 

we than have  fields in the database that don't make sense because it has  amount,  plus attributes, -0 equals some  random number.

**Comment by ChrisFrench** [comment]
This another one that could be looked into whenever. this is actually a rather big problem because it is not really professional. 

What would be nice is if this was part of the when the order was processed  to  payment received or something

**Comment by rdiaztushman** [comment]
I'm closing this one.  Coupons that are added to an order are itemized in the #__ordercoupons table and don't go in the #__orderitems table.  The summed ordercoupons value goes into the parent #__orders table in the order_discount field.  This works the same as the order_subtotal field (sum of orderitems).
