### ISSUE TITLE
GUEST USERS CAN CHECKOUT  ITEMS THAT CHANGE ACL

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#115]
We need to add a check that doesn't let guest users buy items that change the ACL. 

It basically does nothing. 

the other option would be to  make it just create and email them user information when the order is processed.

**Comment by rdiaztushman** [comment]
The latter option is best.  A guest should be able to buy an item that changes their ACL -- we just need to create a user account for them and assign the appropriate acl after checkout.

**Comment by ChrisFrench** [comment]
OK I am working on this

**Comment by ChrisFrench** [comment]
OK this should be working 

909d300d3db7e0cbcbf386b062fa2a59845451cc
