### ISSUE TITLE
Should we clear the orders model cache after a new order is made?

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#117]
Why testing making orders for different things i noticed that I won't see orders come up right away, and I have to clear the cache  to see the new orders. 

This also goes with  Users. 

So  I guess  two questions

should the model cache get cleared whenever there is a save  done in the table?

**Comment by rdiaztushman** [comment]
Yes, the orders model cache should be cleared any time a new order is created.  I thought I had already done this, but maybe I only did it on the admin-side?  Either way, the answer is YES

**Comment by ChrisFrench** [comment]
I think I hadn't updated
