### ISSUE TITLE
if cart amount is 0.00  we should force check  not using a payment method or a free method that gives access right away

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#119]
So in the case that someone uses a coupon to get something for free, we need to force them to not have to select a payment method or maybe have a  free option. 

This is something that someone would use to promote a product most likely a digital download or a subscription service something like that. 

right now if the cart is 0, it forces you to checkout , the only option we would have is to force them into a offline payment method.

maybe we make a brand new payment method  called tienda_payment_free, this could also optionally have  options for "like for a product" integrate with PMINTS something like that

**Comment by rdiaztushman** [comment]
This already happens, but only in the standard checkout process (see line 2000 of the checkout controller).

We just need to update the OPC so that it uses similar logic.

**Comment by ChrisFrench** [comment]
So before I add it to the OPC, do you think we should  remove all that code. add a free payment method plugin?

if we do that than the logic is always the same.

**Comment by ChrisFrench** [comment]
oh you assigned this to you.

**Comment by rdiaztushman** [comment]
Ha, i was committing this fix just as you commented.  Take a look at my commit, git pull, and test.

R

**Comment by ChrisFrench** [comment]
Yea awesome!  another bites the dust.
