### ISSUE TITLE
Tienda Category cache not Cleared when a new item is added

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#124]
So you have to clear the cache manually to see it

**Comment by efillman** [comment]
Can you give me a hint on how to replicate the behaviour? I've got some programming time on my hands this weekend.

**Comment by ChrisFrench** [comment]
You create a new item in the category admin I tried adding clear cache a
few places in the save function but it didn't fix it

**Comment by rdiaztushman** [comment]
I'm jumping in to take a look at this

**Comment by ChrisFrench** [comment]
Please do I added a model clear cache and it didn't work

**Comment by rdiaztushman** [comment]
Hmm, i just created a new category and it showed up immediately.  I need to know exactly how to recreate this.

**Comment by rdiaztushman** [comment]
I went to the category manager.
1) Click New
2) Type in a title ("Paper")
3) Did not select a parent category
4) Click Save

The Paper category was in the list after the save...

**Comment by rdiaztushman** [comment]
You shouldn't need to add a $model->clearCache() to the categories controller's save() function because it calls the parent::save() function, which clears the cache itself.

**Comment by ChrisFrench** [comment]
Hmm strange maybe this is only effecting my local install

**Comment by ChrisFrench** [comment]
Maybe try to create a few if it doesn't happen you cab close this

**Comment by rdiaztushman** [comment]
Definitely can't reproduce, even on http://dev.dioscouri.com/~tienda/administrator/
which is just the checkout of the demo
