### ISSUE TITLE
Graphs don't show up  on HighCharts unless I use inspect to view the items

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#128]
In Chrome, Safari, Firefox, I can't get graphs to show up on load.

it just looks  blank, if  use the inspector to check it, it than loads the  graphs super wierd. 

I tried disabling bootstrap and it had no effect not sure whats up

**Comment by rdiaztushman** [comment]
strangely, graph displays after you resize the window.

**Comment by rdiaztushman** [comment]
Looks like it is a Highcharts issue with our jquery version.  Need to upgrade highcharts in the library
http://stackoverflow.com/questions/6924356/highcharts-jquery-rendering-problem-all-browsers

**Comment by rdiaztushman** [comment]
Fixed by upgrading to v3.4.0 of the DSC library (which uses Highcharts 2.3.3)
