### ISSUE TITLE
Tienda OnePageCheckout has JS error

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#14]
Uncaught ReferenceError: $E is not defined tienda_checkout_onepage.js:27

**Comment by rdiaztushman** [comment]
Same error on standard checkout, line 569 of tienda.js.  Tackling this now because it's impossible to checkout...

**Comment by rdiaztushman** [comment]
This should be fixed with aa787574a41e534b8cb90f07fbe14f4d3b9c644c
Re-open if not!
