### ISSUE TITLE
Long page loading time

### ISSUE THREAD

**Issue by Skullbock** [dioscouri/tienda#146]
When there are 20+ products into a category, and the "show add to cart button in the listing" is enabled, the page load time takes up to 50 seconds in the frontend. I backtraced this issue with the $view->display() of the TiendaHelperProduct::getCartButton() but i wasn't able to check into this more. It's definetly an issue to solve before releasing ;)

**Comment by rdiaztushman** [comment]
What resolved this issue?

**Comment by Skullbock** [comment]
It's related to the other one I opened

Daniele Rosario

Il giorno 01/dic/2012, alle ore 19:04, Rafael Diaz-Tushman <
notifications@github.com> ha scritto:

What resolved this issue?

—
Reply to this email directly or view it on
GitHubhttps://github.com/dioscouri/tienda/issues/146#issuecomment-10919941.
