### ISSUE TITLE
EAV killing queries

### ISSUE THREAD

**Issue by Skullbock** [dioscouri/tienda#148]
In Joomla 2.5 when you're in the category product listing view with the add to cart button enabled, the system takes up to 20 secs for loading the page due to a huge number of queries for the EAV on the products.

I managed to track it down using new relic, and it seems to make a lot of db calls and getList calls each time a product is shown, even if those are not really required (no custom field, and it should do just 1 call per product anyway). Each query and call is very fast, 0.5 ms, but they are beng done so many times that it takes forever to execute

**Comment by rdiaztushman** [comment]
Could this be related to #135?

**Comment by Skullbock** [comment]
I have product compare disabled onmy environmenet, and by my logs it doesn't reach any compare realted methods

**Comment by rdiaztushman** [comment]
Hmm, ok.  Once I wrap up the OPC rebuild (almost done), I'll look at this
