### ISSUE TITLE
One Page Checkout can't  get paymethod don't get displayed

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#15]
This feature works with the same data  using the none one page checkout. 

So there is probably some thing related to the JS error?

**Comment by rdiaztushman** [comment]
This is still an issue.  I'm experiencing it now.  Looking into what causes it

**Comment by ChrisFrench** [comment]
I spent a fair amount of time on this before and nothing was jumping out at me about it I am watching with interest
