### ISSUE TITLE
Checkout Page has Javascript Conflict errors when template uses jQuery

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#160]
If the front end has jQuery you can't checkout because of some  JS errors

**Comment by ChrisFrench** [comment]
Uncaught TypeError: undefined is not a function checkout:614
Uncaught TypeError: Property '$' of object [object Window] is not a function tienda_checkout.js:193
Uncaught TypeError: Property '$' of object [object Window] is not a function tienda_checkout_onepage.js:38

**Comment by rdiaztushman** [comment]
Which checkout type? 

---

**Comment by rdiaztushman** [comment]
Meaning: was this a OPC?  If so, which layout?

**Comment by ChrisFrench** [comment]
Yes this is happening on the one page checkout

**Comment by rdiaztushman** [comment]
Which version of the OPC?  Standard (the new one i just added)?  or 1 column?  or 2 column?  or 3 column?

**Comment by ChrisFrench** [comment]
I will email you details of how to test on my demo site

**Comment by rdiaztushman** [comment]
Needed to load jquery after mootools in template, wasn't a tienda issue.
