### ISSUE TITLE
Adding Geozone taxZone fails on a new install

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#167]
While trying to  add zones  to the tax zone I am getting SQL errors, this is on  a new install

Error: 3613: TiendaTableZonerelations: :store failed
Cannot add or update a child row: a foreign key constraint fails (`tiendademo`.`ppaqj_tienda_zonerelations`, CONSTRAINT `fk_geozone_zonerelations` FOREIGN KEY (`geozone_id`) REFERENCES `ppaqj_tienda_geozones` (`geozone_id`) ON DELETE CASCADE ON UPDATE CASCAD) SQL=INSERT INTO `ppaqj_tienda_zonerelations` (`zone_id`,`geozone_id`,`created_date`) VALUES ('3613','3613','2012-12-15 09:08:10')

**Comment by ChrisFrench** [comment]
This doesn't happen on shipping zones.

**Comment by rdiaztushman** [comment]
Ok, i'm looking at this one now.  The Giants are getting destroyed by the Falcons, so it was painful to watch...

**Comment by rdiaztushman** [comment]
hmm, can't recreate.  going to ping you on skype.

**Comment by rdiaztushman** [comment]
Can't recreate, looks like it was an issue on your installation.
