### ISSUE TITLE
Fatal Error when viewing completed order

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#17]
URL 
http://dev.ammonitenetworks.local/component/tienda/orders/view/3

Error

Fatal error: Cannot access protected property TiendaQuery::$_where in /Users/chris/Documents/Aptana Studio 3 Workspace/ammonitenetworks.com/administrator/components/com_tienda/helpers/manufacturer.php on line 84

**Comment by rdiaztushman** [comment]
I saw the code this bug referenced that you had commented out.  it did nothing, so this issue is closed.
