### ISSUE TITLE
OLD: Email text customization broken

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#18]
In the process of the language updates, I managed to break the Localization/Emails system.

It used to (in 0.9.0) show one string that could be edited ("EMAIL_NEW_ORDER_TEXT").

I can't seem to figure out how it got broken.

Sorry :-(

**Comment by cpaschen** [comment]
History

#6 Updated by Chris French 3 months ago
Status changed from New to Needs Testing

Hey Lukas,

Mikael Colboc is correct, We ran into this exact same problem when updating the language strings in billets.
I commited a fix for this to the trunk you can close the ticket or test and close but i tested it locally just to make sure.

Chris

#5 Updated by Chris DioscouriChris Paschen. 4 months ago

Dan,

No, that has nothing to do with this.
Please create a new ticket with details (and versions that you are using)

Mikael,

Thanks. I'll leave this info for lukas to review.

#4 Updated by Mikael Colboc 4 months ago

Hi Chris,

This admin form is generated by: admin/views/emails/tmpl/form.php

I believe the issue is in the call: $row->strings which comes from: admin/models/emails/php

around line 75: if(stripos( $k, 'EMAIL_') === 0)

it should be updated to something like: if(stripos( $k, 'COM_TIENDA_EMAIL_') === 0)

I cannot test it myself, but I think it might work.

## 

Dan: I don't think your issue is related, plus I can't reproduce it on my version (0.9.1 EAV)

#3 Updated by Dan Hall 4 months ago

By the title of this issue I think I am confirming the same problem or a related problem, but by the description and comments above I can't tell.

When I change the status of an order on an individual order page, select "Send email to customer" and put a custom message in the text area, I get the following when when updating order:

Fatal error: Class 'JMailHelper' not found in /var/www/vhosts/thetennispark.com/httpdocs/administrator/components/com_tienda/helpers/email.php on line 194

Let me know if I need to create a new ticket for this.

#2 Updated by Chris DioscouriChris Paschen. 4 months ago

If you select Localization | E-mails | English (United Kingdom)

in the 'strings' area (below the Language Information) there should at least be one entry there ('"EMAIL_NEW_ORDER_TEXT').

Now there is noting showing there.

(I haven't had time to dig through to determine where that display/form is generated)

#1 Updated by Mikael Colboc 4 months ago

I'd like to help but can you explain this one better ? I don't see what's broken exactly.

**Comment by ChrisFrench** [comment]
This is working in Tienda and in Billets I am closing this ticket, someone reopen it if they find something wrong
