### ISSUE TITLE
While in files please remember to remove .DS. from file paths

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#2]
this is something we don't need anymore and not supported in joomla 3.0

**Comment by ChrisFrench** [comment]
find . -type f | xargs perl -pi -e 's/".DS."/\//g' 
find . -type f | xargs perl -pi -e 's/.DS."/."\//g'

if you run these two lines from terminal it will convert 
JModel::addIncludePath( JPATH_ADMINISTRATOR.DS.'components'.DS.'com_tienda'.DS.'models' );
to be JModel::addIncludePath( JPATH_ADMINISTRATOR.'/components/com_tienda/models' );

but we also need to support double quoted lines as well

If we could write a shell script for this it will be ideal, this is going to be something alot of people are going to need when upgrading their components to 3.0

**Comment by efillman** [comment]
Probably one of the most ridiculous looking scripts I have ever written, but it works. Be very careful where you run it.

##replace text within files
for i in `find .`
do
    ## ".DS." to /
    sed -i 's/\".DS.\"/\//g' $i
    ## DS." to "/
    sed -i 's/DS.\"/\"\//g' $i
    ## ".DS to /"
    sed -i 's/\".DS/\/\"/g' $i
    ## '.DS.' to /
    sed -i 's/'\''.DS.'\''/\//g' $i
    ## DS.' to '/
    sed -i 's/DS.'\''/'\''\//g' $i
    ## '.DS to /'
    sed -i 's/'\''.DS/\/'\''/g' $i
done

**Comment by efillman** [comment]
Branch is pushed as removeds. 127 files modified.

**Comment by ChrisFrench** [comment]
This is awesome, I tested it throughly this morning, and I didn't get any errors I merged the branches
