### ISSUE TITLE
OLD-6278: EAV Custom Fields - textarea - when set to required no data saved

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#21]
Originally reported by Fincent L.

Fieldtype: textarea
Bug: When required is set to 'enabled' ; no data is saved.

**Comment by cpaschen** [comment]
#2 Updated by Chris DioscouriChris Paschen. 8 months ago

Could this be related to #6532?

#1 Updated by Lukas Polak 12 months ago

I can confirm this issue and I know what's causing it, but it wont be that easy to fix it. Therefore, I'm moving this one to 0.8.3.

**Comment by cpaschen** [comment]
This needs to be tested to see if it's still happening on the new 0.10. codebase

**Comment by ChrisFrench** [comment]
This works actually so closing this ticket the  problem is actually different now. The required is not actually required So   I am going to create a new ticket for that.
