### ISSUE TITLE
OLD-6975: POS: Unable to add product to cart if it has a custom date EAV field

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#22]
# Details:

Attempting to add a product to an order via POS results in an error (and product not added to cart) if the product has a custom date field associated with it).

> TiendaTableCarts::store failed - Unknown column 'custom-field-3-date- in 'field list' SQL=INSERT INTO '..._tienda_carts' ('user_id','session_id....

NOTE: The error only appears for a few seconds and then the lighbox closes, without the product being added to the cart.

**Comment by rdiaztushman** [comment]
Moving to the POS milestone because this issue doesn't exist on the front-end.

**Comment by rdiaztushman** [comment]
Chris, I see you were just working on the admin-side POS.  Can you create a custom field of type datetime and test to see if this issue still exists?

**Comment by ChrisFrench** [comment]
Yo you can add the items to cart in the POS but  the POS doesn't support custom fields of any type
