### ISSUE TITLE
OLD-6935: Leaving any 'validation required' field should update the status

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#24]
## Description

If you leave a field blank (like the 'Address Title' field) and then continue completing the form, after entering the 'country' the data is 're-validated' and you get an error notice (no address title).

However, if you go and add an address title, there's no way obvious way to update the order again.

We either need a 'refresh' button or have the validation process run after ANY 'required' field is updated (i.e. when focus leaves that entry box).

[NOTE: Not sure which release this should be placed in - possibly not in 0.9.1]
###### Updated by Chris DioscouriChris Paschen. 6 months ago

Actually, it would probably be a good idea to allow two different methods (with a config option).
1. Automatic update after data is entered
   Run the data verification of all fields after any 'required' field is exited
2. Manual update - add a refresh button
   Have an 'update address' button available on the screen that manually updates the data and runs the test.
3. Both
   Have the data verification run as in #1 AND display a refresh button.

**Comment by rdiaztushman** [comment]
Having worked on the OPC and standard checkout the past few days, I can tell you that we need to make this and several other significant usability improvements to checkout (and the entire front-end interface).

**Comment by rdiaztushman** [comment]
The 'update' button is not going to be the final solution here.  An overhaul is the final solution.  But the button will do for now.
