### ISSUE TITLE
OLD-6932: Keyboard select of country field not synchronized with zone field

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#26]
## Description

Description

If you select a country by:
- Entering "U" for "United States" 
- Press 'down arrow' to then select the 'united states entry'

The Zone Field doesn't get synchronized with the country that is selected (it is still the initial country zones from the first entry in the country list).

If you instead, use the mouse and select the country the list gets synchronized.

This was working properly in 0.8.x series. Broken in 0.9.0

**Comment by ChrisFrench** [comment]
I just tested this again, in one page checkout and chrome and firefox it is still working. it should be working on all other browsers.
