### ISSUE TITLE
OLD-6879: Postal code change (OPC) causes all billing/shipping data to clear

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#28]
## Description

Using OPC-Standard, when you enter and address it works fine, but if you go back and CHANGE the postal code it clears all the name/address fields.
###### Updated by Chris DioscouriChris Paschen. 6 months ago

Assignee changed from Chris DioscouriChris Paschen. to Lukas Polak

Well ... I just tested this from the trunk and still it's having the same issue - the missing postal code notice is not being removed.
###### #8 Updated by Lukas Polak 7 months ago

Status changed from In Progress to Requires Feedback
Assignee changed from Lukas Polak to Chris DioscouriChris Paschen.
###### #7 Updated by Chris DioscouriChris Paschen. 7 months ago

Status changed from Needs Testing to In Progress
Assignee changed from Chris DioscouriChris Paschen. to Lukas Polak
###### #6 Updated by Chris DioscouriChris Paschen. 7 months ago

Nope ... now when you go through the checkout process....
1. (after entering a complete address BEFORE you enter the postal code) you see "Billing Address Error :: Postal Code Required (which is correct at this point.
2. After entering the postal code, the above notice (postal code required) doesn't clear.

Looks almost like the ajax got killed.

NOTE: The form does refresh if I go back and change the Zone (or any other field).

So it looks like it's still broken with this fix.
###### #5 Updated by Lukas Polak 7 months ago

Status changed from Unconfirmed to Needs Testing
###### #4 Updated by Lukas Polak 7 months ago

% Done changed from 0 to 100
Resolution set to Fixed
Documentation Status set to Unnecessary
Affects Template Files changed from No to Yes

Chris, I found the problem :) it was with automatic updates of shipping methods when you changed postal code field and the order did not require shipping (it was not working correctly). Everything should be OK now.

Lukas
###### #3 Updated by Chris DioscouriChris Paschen. 7 months ago

Assignee set to Chris DioscouriChris Paschen.

OK ... I'm only getting this on a fresh Joomla site with a clean Tienda install.

Installing on my older test site (upgrade from previous versions of Tienda - including most pre-releases - this issue doesn't happen).

After the Monday webinar I'll wipe out the old tienda on the other test site and re-install and see if I can duplicate this there.
###### #2 Updated by Chris DioscouriChris Paschen. 7 months ago

Happens on 2-column also.
###### #1 Updated by Chris DioscouriChris Paschen. 7 months ago

Appears to happen on 1-column also.
###### Revision 2501

Added by Lukas Polak 7 months ago

attached AJAX call to Postal Code field during checkout - refs #6879
###### Revision 2479

Added by Lukas Polak 7 months ago

fixed error during tienda uninstallation + fixed problem with postal code + fixed syntax issue with JText in productcompare.php - refs #6870, #6879, #6807

**Comment by rdiaztushman** [comment]
I don't think this one is still valid.  I was just testing the OPC standard and column-layout variations and couldn't recreate this.
