### ISSUE TITLE
OLD-6791: EAV entries have eaventity_type of 'carts' even after order is completed

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#29]
## Details

In testing, using eavvarchar - the eaventity_type is remaining as 'carts' and not 'orderitems'.

In testing I can't identify any specific pattern why this is happening. Almost appears to be either related to a loop counter issue or???

NOTE: The fix in #6776 does NOT appear to change this in any way.
###### Updated by Chris DioscouriChris Paschen. 5 months ago

Assignee changed from Chris DioscouriChris Paschen. to Lukas Polak

OK ... I just tested this again with a completely clean version of Tienda from the trunk (r2559).

Now I'm getting something even more strange.

(First, the 'textarea' is still going into the 'eavValuesText' (instead of the varcar table - which is confusing).

But now I'm getting THREE entries in the _tienda_eavvaluestext table.

Each have successive eavvalue_id values.
2 are set to type 'carts', 1 to 'orderitems.
the eaventity_id is also different for each.
The created_date and modified_dates are blank.

Here's what I'm seeing.

`eavvalue_id    eavattribute_id    eaventity_type table name of the entity    eaventity_id    eavvalue_value    created_date    modified_date
     1    5    carts    3    Add some description here for the subscription.
E...    0000-00-00 00:00:00    0000-00-00 00:00:00
     2    5    orderitems    2    Add some description here for the subscription.
E...    0000-00-00 00:00:00    0000-00-00 00:00:00
     3    5    carts    5    Add some description here for the subscription.
E...    0000-00-00 00:00:00    0000-00-00`
###### #4 Updated by Lukas Polak 6 months ago

Status changed from New to Requires Feedback
Assignee changed from Lukas Polak to Chris DioscouriChris Paschen.

Chris, are you sure that this is still an issue? I tried to reproduce this, but it seems to be working for me. Here is what I tried (and checked table in DB after every step):
- i created a custom field of type text area, assigned it to a product and add the product into cart
- then i proceed to checkout (OPC)
- logged in
- selected shipping & payment method
- click on "Click here to continue" 
- finished order (set as completed in the back-end)

Can you tell me what you did exactly when you experienced this problem?
###### #3 Updated by Chris DioscouriChris Paschen. 7 months ago

Priority changed from Normal to High
###### #2 Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.9.0 - Major Core Fixes to Version 0.9.1 - EAV (Custom Fields) Finalization
###### #1 Updated by Chris DioscouriChris Paschen. 8 months ago

Priority changed from High to Normal
Update Log time Watch Copy Delete

**Comment by ChrisFrench** [comment]
I tested this and I was indeed getting the cart type for a short time, but after the order was processed, or the cart was gone these were also gone I am closing this and opening another ticket for the textarea issue
