### ISSUE TITLE
OLD-6749: Entries in eavvaluesvarchar are not deleted when orders are deleted

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#30]
## Details

the eavvaluesvarchar (and probably other eavvaules_______ tables) are not having their data deleted from the table when an order is deleted.
###### Updated by Chris DioscouriChris Paschen. 7 months ago

Priority changed from Normal to High
###### #1 Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.9.9 - Misc Bug Fixes and New Features to Version 0.9.1 - EAV (Custom Fields) Finalization

**Comment by ChrisFrench** [comment]
haha damnit I had just started this and though I should go assign it to myself

**Comment by rdiaztushman** [comment]
ah ok, i haven't started.  go ahead and finish what you're doing.

**Comment by ChrisFrench** [comment]
Hey Rafael, 

Actually I think you should do this one. 

we should update the orders table to use the tables for each table to do the deletes instead of how it is written right now. 

Thanks

**Comment by ChrisFrench** [comment]
https://github.com/dioscouri/tienda/issues/121

**Comment by rdiaztushman** [comment]
Fixed by 4d4bdb1e42e23e5009d81fc3efd02b442dbbabf3
