### ISSUE TITLE
OLD-4917: lost parent attribute when "save as"

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#31]
## Description

No parent attribute for a new product created by "save as" of a product with partent attribute.

Only a parent links is lost, all attrributes are still alive!
###### Updated by Chris DioscouriChris Paschen. 6 months ago

Status changed from Needs Testing to Requires Feedback
#6 Updated by Chris DioscouriChris Paschen. 6 months ago

Assignee changed from Chris DioscouriChris Paschen. to Lukas Polak

This still doesn't appear to be working here.

(Do I need to wipe the data tables out completely to make this work)?
###### #5 Updated by Lukas Polak 7 months ago

Status changed from New to Needs Testing
Assignee changed from Lukas Polak to Chris DioscouriChris Paschen.
% Done changed from 0 to 100
Resolution set to Fixed
Documentation Status set to Unnecessary
###### #4 Updated by Chris DioscouriChris Paschen. 7 months ago

Priority changed from Low to High
###### #3 Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.9.9 - Misc Bug Fixes and New Features to Version 0.9.1 - EAV (Custom Fields) Finalization
###### #2 Updated by Chris DioscouriChris Paschen. 9 months ago

Assignee set to Lukas Polak
Priority changed from Normal to Low
Affected Version changed from 0.7.0 / 0.8.1 to 0.7.0 / 0.8.1/0.8.3 PreE

Confirmed on 0.8.3 preE

However, there is a workaround - by just re-building the parent relationships.

Lukas - is this something that SHOULD be working (saving the parent relationships) or is this something that should be part of the AttributeTemplate system?
###### #1 Updated by Chris DioscouriChris Paschen. about 1 year ago

Category set to Admin - Product Attributes
Target version set to Version 0.9.9 - Misc Bug Fixes and New Features
Affected Version changed from 0.7.0 to 0.7.0 / 0.8.1
Users to notify set to 13032
Affects Template Files set to No

This is still an issue in 0.8.1.

However, I'm wondering if the Save As function is even capable of saving complex parent/child attributes - or is this something for the enterprise attribute system?
###### Revision 2503

Added by Lukas Polak 7 months ago

preserve attribute's parent relationship when using "save as" feature - refs #4917

**Comment by ChrisFrench** [comment]
I can't reproduce this on the current version, all the attributes were copied over and displayed currently
