### ISSUE TITLE
OLD-6934: JText:: error display needs to be re-configured

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#35]
## Description

in the /admin/tables/addresses.php line 97-120
the address error notice method doesn't work with the new JText language string usage.

The arrays for the $address_checks don't get translated.

We need to re-work this code to properly display error messages and have them be translatable.
###### Updated by Chris DioscouriChris Paschen. 6 months ago

Status changed from New to Requires Feedback
Assignee set to Lukas Polak

Can we just change the last item in each of these 'array' entries to a "JText::_(...)" entry?

**Comment by rdiaztushman** [comment]
This one actually looks like it was already resolved, and quite nicely, whoever did it!!
