### ISSUE TITLE
OLD-6750: EAV Custom Fields TEXT being stored in VarChar table (not text table)

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#39]
## Description

All 'text' fields are being stored in the eavValuesVarchar table, not the ...Text table.

Not sure if this is correct.

(If it is, then why do we have a 'eavValuesText' table?)
###### Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.9.0 - Major Core Fixes to Version 0.9.1 - EAV (Custom Fields) Finalization

**Comment by rdiaztushman** [comment]
Can't reproduce.  They're being stored in the text table.
