### ISSUE TITLE
Inputs elements are too big

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#4]
Input elements of 30px's are to tall, and the don't align well with select lists or graphical buttons. 

they should be smaller 18px i think

**Comment by ChrisFrench** [comment]
i added a small tweak to over ride the library for now to the admin.css for tienda because the library styles were messing up the designs

**Comment by rdiaztushman** [comment]
I left the Tienda CSS definition overriding this in the tienda admin.css file in case we want to tweak this further, but the height can't be 18px -- that obscures the text within the input boxes.  Let me know what styling issues you see when it's at 30px and we'll find a solution, but 18px height isn't working.  Closing this for now.
