### ISSUE TITLE
OLD-3566: Add attribute error returned by server...

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#40]
## Description

Hi

When I add several attribute options to an attribute I stert getting the following error in the popup after I submit:

Fatal error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 207 bytes) in /home/.../public_html/administrator/components/com_tienda/helpers/product.php on line 1087

When I close the popup & click apply the attribute option has been added. At the time this started happening there was two attributes with 80 attribute options each and another 3 attributes still needs to be added with about 20 attribute options each.

I understand that it is a size issue, but is not sure if it is my server's problem or something that needs to be changed in Tienda, So I post it here in the hope it is helpful.

thanks

drifter

VER: 0.56 0.7.3
###### Updated by Lukas Polak 7 months ago

Assignee set to Lukas Polak
###### #5 Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.8.9 - Old issue that have already been fixed to Version 0.9.1 - EAV (Custom Fields) Finalization
Affects Template Files set to No
###### #4 Updated by Chris DioscouriChris Paschen. over 1 year ago

Category set to Admin - Product Attributes
Target version set to Version 0.8.9 - Old issue that have already been fixed
Affected Version changed from 0.56 to 0.56 0.7.3

It appears that this is a server problem, but it appears that it might be caused by Tienda trying to load all of the options and attributes into memory at the same time (speculation).

Once you go over 40 options (total) it starts slowing down and depending on your server configs, can actually time out or error-out.

We need to review how options and attributes are being handled in the lightboxes.
###### #3 Updated by Antonio Scribano over 1 year ago

No, I use 0.70. I have a product with 5 attributes of 12 records (so, in total 60 records).
Any idea?
Thank you!
###### #2 Updated by Chris DioscouriChris Paschen. over 1 year ago

Antonio, are you also using 0.5.6?

If so, please update to 0.7.0 and let us know if this error still exists.
###### #1 Updated by Antonio Scribano over 1 year ago

Same problem:

Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 524288 bytes) in /home/palomarw/public_html/web/administrator/components/com_tienda/helpers/product.php on line 1443

also, the script takes a lot of time.
Thank you

**Comment by rdiaztushman** [comment]
Can't recreate
