### ISSUE TITLE
OLD-852: Add weight to attribute options

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#41]
## Description

It would be great to be able to add additional weight to an attribute option that would then be added to the base weight for shipping purposes.
###### Updated by Chris DioscouriChris Paschen. 6 months ago

Status changed from Needs Testing to Requires Feedback
Assignee changed from Chris DioscouriChris Paschen. to Lukas Polak
###### #10 Updated by Chris DioscouriChris Paschen. 6 months ago

OK ... after doing some more testing it looks like it isn't working.

It's not actually having any effect on the shipping plugin (at least not for the Standard shipping).

Not sure if it should at this point or if we need to now update all the shipping plugins to recognize this new functionality.
(If it is the latter then we need to note that).
###### #9 Updated by Chris DioscouriChris Paschen. 6 months ago

Looks like it's working.

However, we now need to change the 'prefix' column header for the 'price prefix' so that it says "Price Prefix" (similar to the way the "Weight Prefix" appears. [I'll create a new ticket for that.]
###### #8 Updated by Lukas Polak 6 months ago

Status changed from New to Needs Testing
Assignee set to Chris DioscouriChris Paschen.
% Done changed from 0 to 100
Resolution set to Fixed
Documentation Status set to Nonexistent
###### #7 Updated by Chris DioscouriChris Paschen. 7 months ago

Priority changed from Normal to High
###### #6 Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.8.9 - Old issue that have already been fixed to Version 0.9.1 - EAV (Custom Fields) Finalization
Affects Template Files set to No

Not sure if we can get this added in.

To allow EAVs to modify other fields than just price (like weight).

This has been requested quite a bit and really is a basic need (esp. when choosing a size of an item changes the weight - related to shipping).
###### #5 Updated by Cristina Solana about 2 years ago

Cool deal, I look forward to seeing this - hopefully in the near future. :)
###### #4 Updated by Rafael Diaz-Tushman about 2 years ago

We have an idea how this could work -- I saw Daniele do it for a client of Weble's -- but we don't have it ready for the public release yet. It may just be an additional field in the PAO input form and a little additional logic in the shipping plugins, but I'd prefer to put that logic directly in the orders table, so we're still ironing this out...
###### #3 Updated by Cristina Solana about 2 years ago

Any new thoughts on this now that increment 6 is around the corner? I don't see it on the road map is why I ask. I am really looking forward to this one...
###### #2 Updated by Rafael Diaz-Tushman over 2 years ago

Target version set to Version 0.8.9 - Old issue that have already been fixed

We've been internally discussing this. It will require a DB change at the minimum, and may be pushed to Increment 6
###### #1 Updated by Robert G. Mears over 2 years ago

Very important addition.

If a photographer, for example, is selling prints, there would be a base price for the cost of packaging and shipping; the number of prints ordered could add to this amount incrementally. The overall packaging and shipping cost would not be simply X times the number of prints. It would be the base cost + (X times the number of prints). Although this could become quite complicated because there would be a limit to the number of prints one could place in a package; then it would be necessary to start a second package. Also the cost to ship three or four prints might be the same as the cost to ship one. Thresholds.

Rudimentary though it is, the javascript I submitted earlier in FR #94 ( nopercart_rgm.js ) sort of has this worked out for use with Canada Post.
###### Revision 2535

Added by Lukas Polak 6 months ago

added db fields for weight in product attributes to sql install scripts - refs #852
###### Revision 2519

Added by Lukas Polak 6 months ago

product attributes can change product weight - refs #852

**Comment by rdiaztushman** [comment]
Reclassified as a bug because dev has been done but it just isn't working.

**Comment by rdiaztushman** [comment]
Actually, this is indeed working.  PAOs can and do change cartitem and orderitem weights.
