### ISSUE TITLE
OLD-7072: Coupon creates negative cart amount

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#42]
## Description

If a user enters a coupon code for a value that is greater than the amount of the cart, it puts the cart in negative numbers and then causes problems on checkout (at least with paypal).

e.g.

If a coupon is worth $500.00
And the user's cart total is $400.00

If the user enters the coupon, the total in the cart becomes -$100.00.

Then if you click to checkout, and go to paypal, Paypal gives you an error saying that this invoice has already been paid.

We need to have some config options on how to handle this instance. It should be able to be set globally in the config. The two options would be:
1. Limit all coupons to the total value of the cart.
   i.e. the coupon is 'used up' no matter what the value is. So if you use the coupon, it's considered 'used' and no 'credit' is given for the difference in the order.
   Just set the total of the cart to "0.00" if it goes into negative amounts.
2. Give 'store credit' for the difference.
   In the example above, give the user a $100 store credit to be used later.

I thought that we had dealt with this issue a while ago (back in the 0.7.x days), but it appears that it either wasn't resolved ... or I'm just imagining that (I can't find any tickets here that deal with that).

NOTE: I'm adding this to the POS (0.9.2) release because we've also got some tickets there for coupons - so probably should do them together.
###### Updated by Bourreau Clément 23 days ago

Hi,

For some people who want to resolve this problem quickly, i made a rapid fix :
1. In database, add a field named "coupon_subtotal_minimum" as a float (13,2) in #__tienda_coupons table ;
2. Add in /administrator/components/com_tienda/views/coupons/tmpl/form.php at line 162 for example :

`````` <tr>
      <td class="key" align="right" width="100">
          <label for="subtotal_minimum">
                 <?php echo JText::_( 'Minimum Subtotal Required' ); ?>:
          </label>
      </td>
      <td>
           <input id="coupon_subtotal_minimum" type="text" size="30" value="<?php echo @$row->coupon_subtotal_minimum; ?>" name="coupon_subtotal_minimum">
      </td>
  </tr>  ```
3. Add in /components/com_tienda/controllers/checkout.php in function "validateCouponCode" around line 2300 the following code :

```  // Check subtotal minimum
  Tienda::load( 'TiendaHelperCurrency', 'helpers.currency' );

  //Calculate amount of order
  $order =& $this->_order; 

  // set the currency
  $order->currency_id = TiendaConfig::getInstance()->get( 'default_currencyid', '1' ); // USD is default if no currency selected

  // set the shipping method
  $order->shipping = new JObject();
  $order->shipping->shipping_price      = @$values['shipping_price'];
  $order->shipping->shipping_extra      = @$values['shipping_extra'];
  $order->shipping->shipping_name       = @$values['shipping_name'];
  $order->shipping->shipping_tax        = @$values['shipping_tax'];

  // get the items and add them to the order
  Tienda::load( 'TiendaHelperCarts', 'helpers.carts' );
  $items = TiendaHelperCarts::getProductsInfo();
  foreach ($items as $item)
  {
      $order->addItem( $item );
  }

  $order->calculateTotals();

  //Check order_total
  if ($order->order_total < $coupon->coupon_subtotal_minimum)
  {
      $response['error'] = '1';
      $response['msg'] = $helper->generateMessage( sprintf( JText::_("SUBTOTAL_MINIMUM_REQUIRED_NOT_REACHED") , TiendaHelperCurrency::currency($coupon->coupon_subtotal_minimum) ) );
      echo json_encode($response);
      return;
  }```
4. Add in translate file traduction of "SUBTOTAL_MINIMUM_REQUIRED_NOT_REACHED" without forget "%s"

Perhaps it's not the best way but if it can help some one...
``````

**Comment by rdiaztushman** [comment]
I remember addressing this a couple years ago (i can't believe I can say that about...) so I'll take a look at this.  The way I had done it way-back-when was to adjust the value of the coupon based on the order's subtotal at the time of adding the coupon to the cart.  No new DB values necessary.
