### ISSUE TITLE
OLD-6470: Coupon - per product - not passed to Paypal std

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#44]
## Description

When using a per-product coupon and the paypal standard payment plugin, the coupon amount is not being reflected in the paypal amount.

It appears that the amount being passed to paypal is just the original amount, without the coupon discount.

NOTE: This was tested on 2 sites and with both the std and OPC checkout.

ALSO: Tested with clean sites (no template overrides, etc.)
###### Updated by Chris DioscouriChris Paschen. 7 months ago

Target version changed from Version 0.9.0 - Major Core Fixes to Version 0.9.2 - POS Finalization

I'm moving this to 0.9.2 - with the POS because we need to work with coupons into POS. (And POS deals with checkout issues where the coupons will be used).
###### #10 Updated by Chris DioscouriChris Paschen. 8 months ago

Status changed from Needs Testing to In Progress

This still appears to be happening.

Although, this might be related to #5168.

Probably best to get that resolved first to see if this is then also resolved.
###### #9 Updated by Chris DioscouriChris Paschen. 9 months ago

OK ... issues 1 & 2 that you mention are related to the re-work.
However, issue 3 is related to another issue (possibly config) that has been addressed earlier.
However, it may be related to an incorrect value being passed.

Let's get the re-work done and then we'll test again for #3.
###### #8 Updated by Neil Mangan 9 months ago

Our Dev site is currently connected to live PayPal. Since we control the PayPal account, we have found it easier and faster to test with real low value test products (eg. $0.05).

Good luck with the re-work!
###### #7 Updated by Chris DioscouriChris Paschen. 9 months ago

Neil,

We've actually found some other issues in the plugin now that will require some significant re-working. We're trying to get those done now.

Just curious about #3 - are you using the Paypal sandbox or live?
###### #6 Updated by Neil Mangan 9 months ago

Tested 0.8.3 pre-release E on our Dev site, using standard checkout and a coupon for 100% off one of the two products in the cart. I encountered several problems:

1) After applying coupon in the '2. Select Payment Method' section of the checkout, the line item notes 'Coupon Discount Applied!', but there is no change to the price in the Price, Sub-Total or Total sections.

2) Under 'Billing Information -> Total Amount Due' the total due refers to the Sub-total amount, excluding taxes etc.

3) When proceeding to PayPal Standard (to see if the correct post-coupon amount is passed through), upon redirect to PayPal, I receive the message 'This invoice has already been paid. For more information, please contact the merchant.'

Upon return to the site using the PayPal button to return to merchant, I am redirected back to my dev site and the Canceled Transaction message page. The order is in Tienda, but with 'pre-payment' status.
###### #5 Updated by Chris DioscouriChris Paschen. 9 months ago

Status changed from New to Needs Testing

OK ... we're now testing with 0.8.3 pre-release E (available in the files area here)

This should be fixed in that version.

If you're able, please test again with that version (although do NOT put this on a production site)
###### #4 Updated by Neil Mangan 9 months ago

Chris DioscouriChris Paschen. wrote:

Neil - what version were you testing with?

Sorry, forgot to add that... version 0.8.2
###### #3 Updated by Chris DioscouriChris Paschen. 9 months ago

Neil - what version were you testing with?
###### #2 Updated by Neil Mangan 9 months ago

Have replicated this bug on a site using Paypal Standard and regular checkout.
###### #1 Updated by Chris DioscouriChris Paschen. 11 months ago

Target version changed from Version 0.9.9 - Misc Bug Fixes and New Features to Version 0.9.0 - Major Core Fixes
###### Revision 2293

Added by Lukas Polak 10 months ago

fixing problem with coupons and their js - refs #6470

**Comment by ChrisFrench** [comment]
The Problem with this is that the plugin pulls the items  with normal prices, and than  adds them to the order, and than displays the discounted total from the checkout. But  we need to add the discounted amount PER Item, because paypal calcs the total  from the items not the totals. 

This have been fixed.
