### ISSUE TITLE
OLD-5168: Tax not being recalculated after coupon applied

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#46]
## Description

After applying a coupon, the tax charged in the cart, and throughout transaction, does not recalculate to reflect the discounted product price. Tax must be recalculated before checkout completes.

"_Apply Coupon Discount Before Tax_" under General Configuration -> Coupon Settings is set to '_Yes_'

5168_-_coupons.png.png (40 kB)   Chris DioscouriChris Paschen., 02/03/2012 03:48 pm
###### Updated by Chris DioscouriChris Paschen. 7 months ago

Target version changed from Version 0.9.0 - Major Core Fixes to Version 0.9.2 - POS Finalization

Moving to 0.9.2 with the POS (and other coupon issues).
###### #22 Updated by Chris DioscouriChris Paschen. 7 months ago

NOTE: Just tested on my test site using code 'd50'.

The coupon gets applied, but the taxes stay the same.

Taxes need to decrease after coupon is added.
###### #21 Updated by Chris DioscouriChris Paschen. 7 months ago

Status changed from Requires Feedback to In Progress
Assignee changed from Chris DioscouriChris Paschen. to Lukas Polak
###### #20 Updated by Chris DioscouriChris Paschen. 7 months ago

Flat Rate, Per Order
###### #19 Updated by Lukas Polak 7 months ago

Status changed from In Progress to Requires Feedback
Assignee changed from Lukas Polak to Chris DioscouriChris Paschen.

Can anybody tell me what kind of coupon are they using when the tax is not recalculated? I cant reproduct this problem on my localhost :/

Lukas

Chris DioscouriChris Paschen. wrote:

Neil,

Actually, the 'prepaid voucher' would be related to the 'store credit' system (that is already part of Tienda), not the coupon system.

And yes, the coupon system should work as you expect ... it's still having problems though.
###### #18 Updated by Chris DioscouriChris Paschen. 8 months ago

Neil,

Actually, the 'prepaid voucher' would be related to the 'store credit' system (that is already part of Tienda), not the coupon system.

And yes, the coupon system should work as you expect ... it's still having problems though.
###### #17 Updated by Rod Farrell 8 months ago

FYI, In Australia tax (GST) is calculated on the actual amount paid. If a coupon represents a discount the the tax should reduce.

If the coupon is is a prepaid voucher then the purchase price is not changing, only the method of payment therefore in that case the tax would not change. I would tend to stay away from the prepaid concept as this gives rise to a whole new world of bookkeeping pain where the store owner is deemed to be holding money on deposit for the voucher purchaser until it is spent etc, etc, etc.
###### #16 Updated by Chris DioscouriChris Paschen. 8 months ago

Status changed from Needs Testing to In Progress
Assignee changed from Chris DioscouriChris Paschen. to Lukas Polak
Resolution deleted (Fixed)

I just tested this with preJ and the taxes are still not changing.

When I enter a coupon code, the Discount is taken off the total of the order, but the taxes don't change.

The taxes need to be re-calculated on the Subtotal minus the discount (after the discount code is entered).

NOTE: I tested on all OPC layouts, and on std checkout. All are having this problem still.
###### #15 Updated by Lukas Polak 8 months ago

Status changed from In Progress to Needs Testing
Assignee changed from Lukas Polak to Chris DioscouriChris Paschen.
Resolution set to Fixed

Error fixed in r2402
###### #14 Updated by Chris DioscouriChris Paschen. 8 months ago

that error is on line tienda.js:797
###### #13 Updated by Chris DioscouriChris Paschen. 8 months ago

Status changed from Needs Testing to In Progress
Resolution deleted (Fixed)

Still having a problem with this.

Now ... when you click 'add coupon to order' the "Discount" line is added, and then the coupon code area is grayed out 'processing', but the taxes don't get updated.

I get:
Uncaught TypeError: Cannot call method 'setStyle' of null
(after pressing the 'Add Coupon to Order'.
Although this error appears to happen before the product review box gets updated.
###### #12 Updated by Chris DioscouriChris Paschen. 8 months ago

Status changed from In Progress to Needs Testing
###### #11 Updated by Lukas Polak 8 months ago

Chris DioscouriChris Paschen. wrote:

Ooops ... forgot to add...

The error that I get on the never ending validation is "$(container) is null on tienda.js:797

This should be fixed in r2388 :) Now I'm going to fix the rest.

Lukas
###### #10 Updated by Chris DioscouriChris Paschen. 8 months ago

Ooops ... forgot to add...

The error that I get on the never ending validation is "$(container) is null on tienda.js:797
###### #9 Updated by Chris DioscouriChris Paschen. 8 months ago

File 5168_-_coupons.png.png added
Status changed from Needs Testing to In Progress
Assignee changed from Chris DioscouriChris Paschen. to Lukas Polak

Looks like there are still some 'issues' in this one.

After you enter the discount code and click the button (see screen shot):

The 'discount' line IS added to the order
Tax amount did NOT change
Total of order DID change (although it has the wrong tax amount included).
Never-ending validation on the coupon code area

The main issues remaining:
1. The tax amount should reflect the subtotal minus the discount
2. The coupon code validation needs to be resolved.
###### #8 Updated by Chris DioscouriChris Paschen. 9 months ago

NOTE - If you LEGALLY can offer a coupon that actually discounts the tax amount collected for your government, please let us know. We did some initial research (as well as over a year talking with users) and we can't find any place where this is permitted (greedy governments! :-) ).
But if you've got a government that allows discounting the tax rate, we'd love to know so that we can add that feature back in (and consider moving there too :-) )
###### #7 Updated by Lukas Polak 9 months ago

Affects Template Files changed from No to Yes
###### #6 Updated by Lukas Polak 9 months ago

Status changed from In Progress to Needs Testing
Assignee changed from Lukas Polak to Chris DioscouriChris Paschen.
% Done changed from 0 to 100
Resolution set to Fixed
Documentation Status set to Nonexistent

Due to possible legal issues in some countries, we deleted an option to apply coupons after tax calculation so now, coupons are always applied before tax calculation.

Lukas
###### #5 Updated by Lukas Polak 9 months ago

Status changed from New to In Progress
###### #4 Updated by Chris DioscouriChris Paschen. 9 months ago

Category set to Admin - Coupons
Priority changed from Normal to High
Target version changed from Version 0.9.9 - Misc Bug Fixes and New Features to Version 0.9.0 - Major Core Fixes
Affected Version changed from 0.7.1 to 0.7.1 \ 0.8.3 preE

Just confirmed that this is still an issue - this makes coupons non-useable.
###### #3 Updated by Chris DioscouriChris Paschen. about 1 year ago

Target version changed from Version 0.8.1 - Bug Fixes to Version 0.9.9 - Misc Bug Fixes and New Features
###### #2 Updated by Lukas Polak about 1 year ago

Assignee set to Lukas Polak
Affects Template Files set to No
###### #1 Updated by Lukas Polak over 1 year ago

Target version set to Version 0.8.1 - Bug Fixes
###### Revision 2403

Added by Lukas Polak 8 months ago

using JText in JS - refs #6695
fixing js error in checkout - refs #5168
###### Revision 2369

Added by Lukas Polak 9 months ago

updating language base - refs #5168
###### Revision 2368

Added by Lukas Polak 9 months ago

fixed problem with tax calculation after applying coupons and tax calculation in general (feature "apply coupon before tax calculation" was removed) - refs #5168

**Comment by ChrisFrench** [comment]
I just tested this. 

it is working correctly,  When applying a coupon code you get  the discount and the taxes are also based on the new price
