### ISSUE TITLE
OLD-6938:Delete cart items not working with CHROME- POS

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#48]
## Description

in POS Delete cart itemes not working with browser CHROME
### Updated by Chris DioscouriChris Paschen. 5 months ago

Status changed from Unconfirmed to New
Affected Version changed from 0.9.0 to 0.9.0 -0.9.1 r2561

Just confirmed this here.

It appears to be effecting both the ability to remove items AND adjust the quantities.
(Maybe something related to the buttons themselves - as the checkbox and the quantity fields work properly).

NOTE: It also doesn't work in Safari on Windows or IE9. I can only get to actually work on FF
### #1 Updated by Chris DioscouriChris Paschen. 6 months ago

Category set to Admin - POS
Status changed from New to Unconfirmed
Target version set to Version 0.9.2 - POS Finalization

**Comment by ChrisFrench** [comment]
87481ad656373e27631763c752e2c5237e9d988c
