### ISSUE TITLE
OLD-6423: Remove unneeded buttons on POS

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#54]
## Description

At the end of the POS process, many different toolbar buttons appear:
Save+New, Save, etc.

I don't think that there is any reason to have a 'save' functionality on that page because the order has already been 'saved' and processed by the time you see that button.

I think all we really need is a 'new' button (in case you want to start a new order).

(In addition, if you click the save+new you get a 500 error).
### #2 Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.9.9 - Misc Bug Fixes and New Features to Version 0.9.2 - POS Finalization
### #1 Updated by Lukas Polak 9 months ago

Assignee set to Chris DioscouriChris Paschen.
Target version changed from **\* NEED YOUR VOTE **\* to Version 0.9.9 - Misc Bug Fixes and New Features

Chris, this is part of POS testing, i was talking about yesterday. We should get rid of these obvious things before we go stable. Can you please test this and write down, which buttons should be removed?

Lukas

**Comment by ChrisFrench** [comment]
This doesn't happen anymore

**Comment by ChrisFrench** [comment]
wait yes it does
