### ISSUE TITLE
OLD-6389: Remove from cart/update quantities not working in POS

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#55]
## Description

The remove from cart and update quantities doesnt work in the backend. I have to login from the frontend as that user, and remove them from there.
### #5 Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.9.9 - Misc Bug Fixes and New Features to Version 0.9.2 - POS Finalization
### #4 Updated by Chris DioscouriChris Paschen. 9 months ago

Status changed from Unconfirmed to New
### #3 Updated by Chris DioscouriChris Paschen. 12 months ago

Target version set to Version 0.9.9 - Misc Bug Fixes and New Features

Confirmed it here also on 0.8.2.
### #2 Updated by Jimmy Anderson 12 months ago

This is still happening on the Backend on 0.8.2. tried on two sites.

On 3/11/2011, at 7:42 AM, projects@dioscouri.com wrote:

Issue #6389 has been updated by Chris Paschen.
Status changed from New to Unconfirmed
Jimmy, can you please test this with 0.8.2?
### #1 Updated by Chris DioscouriChris Paschen. 12 months ago

Status changed from New to Unconfirmed

Jimmy, can you please test this with 0.8.2?

**Comment by ChrisFrench** [comment]
I figured out the problem. 

It is that the buttons have onclick events,  in chrome or some other browsers it doesn't the the buttons value  along with  the form. in firefox it does send the values of the buttons, what I did was  just created two different functions and that fixes it.

**Comment by ChrisFrench** [comment]
87481ad656373e27631763c752e2c5237e9d988c
