### ISSUE TITLE
OLD-6070: POS - Remove Selected button not functioning

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#56]
## Description

To remove items from a POS cart you need to go to the frontend and delete it and then go back to the backend.

Screenshot.png (100 kB)   Gerald Zalsos, 08/19/2011 10:02 am
### #4 Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.9.9 - Misc Bug Fixes and New Features to Version 0.9.2 - POS Finalization
### #3 Updated by Chris DioscouriChris Paschen. about 1 year ago

Target version changed from Version 0.8.1 - Bug Fixes to Version 0.9.9 - Misc Bug Fixes and New Features
### #2 Updated by Chris DioscouriChris Paschen. about 1 year ago

Subject changed from Cant remove items from POS cart to POS - Remove Selected button not functioning
Category set to Admin - Order Management
Target version set to Version 0.8.1 - Bug Fixes

This is confirmed on 0.7.4 pre-release.
### #1 Updated by Gerald Zalsos about 1 year ago

File Screenshot.png added

You can still delete/update the cart.... It's basically the same in the front end...
Kindly see attached screenshot.

**Comment by ChrisFrench** [comment]
the remove cart option works just fine in firefox and not in chrome how is that even possible?

**Comment by ChrisFrench** [comment]
87481ad656373e27631763c752e2c5237e9d988c
