### ISSUE TITLE
OLD-6000: POS - Attributes don't dynamically update process in lightbox

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#59]
## Description

When you change attributes that effect the product price the price is not updated as you change the attributes while in the light box.

(The product price DOES get updated correctly in the cart after you close the lightbox).
### #2 Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.9.9 - Misc Bug Fixes and New Features to Version 0.9.2 - POS Finalization
### #1 Updated by Chris DioscouriChris Paschen. about 1 year ago

Target version changed from Version 0.8.9 - Old issue that have already been fixed to Version 0.9.9 - Misc Bug Fixes and New Features

**Comment by polakluk** [comment]
Fixed
