### ISSUE TITLE
OLD-5777: Create a COMPLETE product delete function

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#60]
## Description

If a product is deleted, its productattributes and productattributeoptions are not deleted from database
### #10 Updated by Chris DioscouriChris Paschen. 6 months ago

Target version changed from Version 0.9.1 - EAV (Custom Fields) Finalization to Version 0.9.2 - POS Finalization

We need to move this one down in priority at this point.
### #9 Updated by Chris DioscouriChris Paschen. 7 months ago

Priority changed from High to Normal
Target version changed from **\* NEED YOUR VOTE **\* to Version 0.9.1 - EAV (Custom Fields) Finalization

Alessandro,

Thanks for pointing that out.

we've had some delays in getting 0.9.1 out the door, so I think we might have time to at least look at this and consider it.
### #8 Updated by Alessandro Manfré 7 months ago

Hi chris,
maybe this feature could be implemented 
Version 0.9.1 - EAV (Custom Fields) Finalization or \* Code Refactoring/Rebuilding *
### #7 Updated by Chris DioscouriChris Paschen. about 1 year ago

Priority changed from Normal to High

Yes, it's a 'feature' because the code was never intended to delete all the other related entries.
(it may have been 'poor design' but that's how it was designed to work).

It doesn't necessarily mean that it will not be done but it will require completely new coding to handle this.
### #6 Updated by Alessandro Manfré about 1 year ago

Sorry Chris, are you sure this is a feature?

from my point of view is bug, a minor bug of course, but with this issue the size of database can be increase to much.
### #5 Updated by Chris DioscouriChris Paschen. about 1 year ago

Tracker changed from Bug to Feature
Subject changed from Incomplete delete product to Create a COMPLETE product delete function
Category set to Admin - Product Management
Target version changed from Version 0.8.9 - Old issue that have already been fixed to **\* NEED YOUR VOTE ***
Affects Template Files set to No
### #4 Updated by Alessandro Manfré about 1 year ago

also productquantities are not deleted completly
### #3 Updated by Chris DioscouriChris Paschen. over 1 year ago

Also, delete (or have option to delete) all product images and attached files. (And remove directories).
### #2 Updated by Chris DioscouriChris Paschen. over 1 year ago

Target version changed from Version 0.8.1 - Bug Fixes to Version 0.8.9 - Old issue that have already been fixed

This is going to require a significant amount of code to do right (to ensure all related data is deleted, but only if it dosen't cause a problem with existing orders).
### #1 Updated by Chris DioscouriChris Paschen. over 1 year ago

Target version set to Version 0.8.1 - Bug Fixes

Also need to check first to not allow delete if product is in use on any orders (to prevent order display problems).

**Comment by ChrisFrench** [comment]
I think before anyone starts on this, we need to recap all the updates, and discuss what we want to do, if we do make a delete function that goes through all the tables and removes data, make sure we use the tables delete function for each table that  has data removed. 

also we need to have checks that make sure that  it doesn't delete a product that has ever been ordered.

**Comment by rdiaztushman** [comment]
Reclassified as a bug, assigned to me, moved out of the POS milestone.

**Comment by rdiaztushman** [comment]
Fixed by commit aa93ad4234925455e720001eb371cc892ef8f7af
