### ISSUE TITLE
OLD-6937: Error message on OPC 'Click Here to Continue' needs to consider current state

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#62]
## Description

Right now, (when using OPC) if you click on the Click Here to Continue button while there is some missing billing/shipping info, a message appears above the 'click here' button that says 'Please select payment method'; however, you can't select a payment method - because one isn't presented yet (the payment method area is saying that there is a 'billing address error').

The check when the button is clicked needs to first check to see if an error has been raised for the shipping or payments area and if so, display an error message that tells you to resolve that issue first (or even just display that error message directly).

**Comment by rdiaztushman** [comment]
Is this still an issue?

**Comment by rdiaztushman** [comment]
I answered my own question.  This does happen, but since it's a UI issue that will be resolved when I rebuild the checkout, i'm closing this in favor of #132

**Comment by rdiaztushman** [comment]
refs #132
