### ISSUE TITLE
OLD-6351: Child Item displays (in parent item listing) don't respect qty restrictions

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#63]
## Description

If you set qty restrictions in a child item, you can still change the qty - without regard to the qty rules - when the item is listed in a parent item.
### #5 Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.9.0 - Major Core Fixes to Version 0.9.2 - POS Finalization
### #4 Updated by Chris DioscouriChris Paschen. 8 months ago

Priority changed from Normal to Low
### #3 Updated by Chris DioscouriChris Paschen. 9 months ago

Status changed from In Progress to New
### #2 Updated by Chris DioscouriChris Paschen. 9 months ago

Status changed from New to In Progress
### #1 Updated by Chris DioscouriChris Paschen. 9 months ago

Assignee set to Lukas Polak

**Comment by rdiaztushman** [comment]
Turns out this is a larger issue.  Regardless of whether or not the product is a child of another product, I see no evidence of the quantity restrictions being enforced during add to cart NOR from within the update-cart view.
