### ISSUE TITLE
Add config value to force order tax calculation based on shipping geozone (OLD-1439)

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#64]
## Description

In Canada, as far as sales taxes go, what matters is where the goods are received; ie: where they are shipped to. 
Hence the tax rate needs to be attached to the shipping address not the customer's billing address if it is different.

For example, if I live in Alberta but I'm buying something as a gift for my niece in New Brunswick and having the Tienda vendor ship it to her, the sales tax should be calculated for New Brunswick.
### #5 Updated by Chris DioscouriChris Paschen. 8 months ago

Users to notify set to 13505
### #4 Updated by Robert G. Mears 8 months ago

Great.
### #3 Updated by Chris DioscouriChris Paschen. 8 months ago

Status changed from Needs Testing to New
Priority changed from Urgent to Immediate
Target version changed from Version 0.9.0 - Major Core Fixes to Version 0.9.3 - Admin Interface Cleanup

I just tested and this is still an issue.

Legally, in the US, Canada, and many other parts of the world, the tax is legally supposed to be calculated based on 'the point where the purchaser takes possession of the product'.

Right now taxes are being automatically calculated based upon the billing address, which is not legal.

Ideally we should have a general config option of 'tax location', with options for 'billing' and 'shipping'. With the 'shipping' set as the default.
However, it needs to look to see if there is a shipping address indicated (i.e. is this a physical product or not). If it is not physical (i.e. no shipping address for this order) then it needs to use the billing.

[Maybe we should just always store a shipping address. Just if there is no shipping it wouldn't display. Only be there for reference for tax purposes.]

We need to have this fixed for the 1.0 release.
### #2 Updated by Chris DioscouriChris Paschen. 8 months ago

Status changed from New to Needs Testing
Assignee set to Chris DioscouriChris Paschen.
Priority changed from Normal to Urgent
Target version changed from Version 0.8.9 - Old issue that have already been fixed to Version 0.9.0 - Major Core Fixes
Affects Template Files set to No

I need to test to see how taxes are presently being applied (billing or shipping)
### #1 Updated by Rafael Diaz-Tushman about 2 years ago

Category set to Plugins - Other
Target version set to Version 0.8.9 - Old issue that have already been fixed

**Comment by rdiaztushman** [comment]
Seems like this one can be addressed easily enough with a config value.
