### ISSUE TITLE
OLD-6856: Non-user friendly error message

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#69]
## Description

In "Select Zones" if you click on change status without selecting any items you get the following error message. Not technically wrong but a more user friendly message like "You must first select a zone" would be better.

```
Error: 0: TiendaTableZonerelations::store failed - Cannot add or update a child row: a foreign key constraint fails (`tiendatest`.`jos_tienda_zonerelations`, CONSTRAINT `fk_geozone_zones` FOREIGN KEY (`zone_id`) REFERENCES `jos_tienda_zones` (`zone_id`) ON DELETE CASCADE ON UPDATE CASCADE) SQL=INSERT INTO `jos_tienda_zonerelations` ( `zone_id`,`geozone_id`,`created_date` ) VALUES ( '0','2','2012-03-07 05:53:50' )
```
### #3 Updated by Chris DioscouriChris Paschen. 8 months ago

Category set to Admin - Zones and Geozones
Status changed from Unconfirmed to New
Target version set to Version 0.9.3 - Admin Interface Cleanup

AHHH ... thanks for catching that! I've confirmed that on test site here.

We need to add an error check to make sure SOMETHING is selected before trying to run the SQL there.

We'll get that in the admin cleanup round.
### #2 Updated by Rod Farrell 8 months ago

Geo Zones / Select Zones
### #1 Updated by Chris DioscouriChris Paschen. 8 months ago

Status changed from New to Unconfirmed

Rod,

What screen is this on? Geo Zones? Shipping Config?

**Comment by ChrisFrench** [comment]
This should be fixed Thanks Rod
