### ISSUE TITLE
OLD-6514: Order Payments - Type Status shows reference not text

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#72]
## Description

The Order Payments 'Orderpayment Type' field shows the reference (i.e. 'payment_offline') instead of the text phrase.
### #2 Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.9.9 - Misc Bug Fixes and New Features to Version 0.9.3 - Admin Interface Cleanup
### #1 Updated by Chris DioscouriChris Paschen. 10 months ago

Target version set to Version 0.9.9 - Misc Bug Fixes and New Features

**Comment by ChrisFrench** [comment]
This is done
