### ISSUE TITLE
OLD-6195: Admin Submenu - Adding an entry via PHP causes duplicate menu items

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#73]
## Description

The following wiki page gives instructions on how to dynamically add a submenu item using PHP:

[[http://projects.dioscouri.com/projects/tienda/wiki/Add_a_Submenu_Item_to_Tienda]]

Using this information I added code to insert a new submenu item. The new menu item is added okay, however, all of the existing submenu items defined in the xml file are duplicated in the submenu. See the attached image.

I tested my code in a plugin and and in a view and had the same results.

```
$menu_name = 'submenu_configuration'; // this could be leftmenu_localization or any name that corresponds to an xml menu file
$menu = TiendaMenu::getInstance( $menu_name );
$menu->addEntry('Whatever3', 'index.php?option=com_whatever');
```

If I add a menu item to the left menu, then the items are not duplicated.

duplicate_menu_items.png (20 kB)   Marty E, 09/10/2011 02:10 pm
### #4 Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.9.9 - Misc Bug Fixes and New Features to Version 0.9.3 - Admin Interface Cleanup
### #3 Updated by Chris DioscouriChris Paschen. about 1 year ago

OK ... we'll look at this as part of 0.8.2.

FYI ... because this isn't critical, and we're trying to take care of some 'critical' issues right now, this might take a couple/few weeks before it is resolved.
### #2 Updated by Marty E about 1 year ago

The XML method works, however, I would like to avoid modifying any of the tienda core files.

I have the mootools upgrade plugin enabled.
### #1 Updated by Chris DioscouriChris Paschen. about 1 year ago

Category set to Administration
Target version set to Version 0.9.9 - Misc Bug Fixes and New Features

Marty,

That WIKI is quite old (ver 4.4), and I'm pretty sure we've changed the admin-side 'system' a bit since then.

I'm not sure that the PHP method is still supported.

Have you tried the XML method (I know that might not do what you need, but just wondering if you've tried).

Also, do you have the mootools upgrade plugin enabled?

**Comment by ChrisFrench** [comment]
I just recently did this for a project I am working on and I confirm it is indeed fixed however the wiki or method should be updated to use the library. 

The example code would look lik this. 

https://gist.github.com/3990893

I created a tienda plugin and used it to add to the menu  before the component is displayed.
