### ISSUE TITLE
OLD-6840: Improve Ant Build.xml file to update version numbers

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#74]
## Description

Update the build file so that when you enter the version number during the build process - it automatically updates all the files in the release (i.e. manifest, etc.) and tags the version (IF that is even possible from an ANT build file)

**Comment by rdiaztushman** [comment]
This one is totally for Evan :-)

**Comment by efillman** [comment]
You can now use @VERSION@ and @TIMESTAMP@ in any file and it will tokenize with the ant build. Currently just added tokens to manifest files.
