### ISSUE TITLE
OLD-2564: Use unique form names, no adminForm

### ISSUE THREAD

**Issue by cpaschen** [dioscouri/tienda#75]
## Description

adminForm poses too many potential conflicts, so we should use unique form names
### #12 Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.9.9 - Misc Bug Fixes and New Features to Version 0.9.3 - Admin Interface Cleanup
### #11 Updated by Chris DioscouriChris Paschen. 8 months ago

Target version changed from Version 0.9.0 - Major Core Fixes to Version 0.9.9 - Misc Bug Fixes and New Features
### #10 Updated by Chris DioscouriChris Paschen. 9 months ago

Priority changed from Normal to Low
### #9 Updated by Chris DioscouriChris Paschen. 9 months ago

Assignee set to Lukas Polak
Target version changed from Version 0.9.9 - Misc Bug Fixes and New Features to Version 0.9.0 - Major Core Fixes
Affects Template Files set to No

Lukas - is this just refering to the class name?

Could we just replace all 'adminForm' occurrances with 'TiendaAdminForm'?

(using search/replace in aptana?)

Or am I missing something here?
### #8 Updated by Chris DioscouriChris Paschen. about 1 year ago

Target version changed from Version 0.8.1 - Bug Fixes to Version 0.9.9 - Misc Bug Fixes and New Features
### #7 Updated by Rafael Diaz-Tushman over 1 year ago

Target version changed from Version 0.6.3 - New Features and Bug Fixes to Version 0.8.1 - Bug Fixes
### #6 Updated by Rafael Diaz-Tushman almost 2 years ago

Target version changed from Version 0.6.1 - New Features and Bug Fixes to Version 0.6.3 - New Features and Bug Fixes
### #5 Updated by Rafael Diaz-Tushman almost 2 years ago

Target version changed from Version 0.6.0 - New Major Features and Bug Fixes to Version 0.6.1 - New Features and Bug Fixes
### #4 Updated by Rafael Diaz-Tushman almost 2 years ago

Subject changed from Use unique form names to Use unique form names, no adminForm
### #3 Updated by Rafael Diaz-Tushman about 2 years ago

Target version changed from Version 0.5.6 - New Minor Features and Bug Fixes to Version 0.6.0 - New Major Features and Bug Fixes
### #2 Updated by Rafael Diaz-Tushman about 2 years ago

Target version changed from Version 0.5.5 - New Minor Features and Bug Fixes to Version 0.5.6 - New Minor Features and Bug Fixes
### #1 Updated by Rafael Diaz-Tushman about 2 years ago

Target version changed from Version 0.5.4 - New Minor Features and Bug Fixes to Version 0.5.5 - New Minor Features and Bug Fixes
### Revision 839

Added by Rafael Diaz-Tushman about 2 years ago

Cleaned up default template
fixes #3158: Add to cart button in product listings
refs #2910: Content Plugin product_buy forms need to have unique names
refs #2564: Use unique form names

**Comment by ChrisFrench** [comment]
Chris P, is this something we actually want to do anymore, I think we should probably leave them as adminForm and than follow the joomla 3.0 guidelines and add this . 

Forms that have name="adminForm" now also require id="adminForm".

**Comment by ChrisFrench** [comment]
I am going to go with we leave adminForm, and than add the ID  as well as joomla docs say to do. Closing this
