### ISSUE TITLE
Payment YES / NO boxes UI is broken on items generated by JFORM

### ISSUE THREAD

**Issue by ChrisFrench** [dioscouri/tienda#8]
we just need to create a custom style for these so they look and act like the yes and no buttons above

**Comment by ChrisFrench** [comment]
http://LOCALHOST.local/administrator/index.php?option=com_tienda&view=payment&task=edit&id=10487

administrator/index.php?option=com_tienda&view=payment&task=edit&id=10487

**Comment by ChrisFrench** [comment]
Evan, can you handle this one? I think it is ok if you just jQuery to manipulate it into having the right structure or classes to make them look right.

**Comment by efillman** [comment]
got this one squashed. I think I accidentally committed to the remove ds branch I had made previously. This also begs the question if we need to add a wrapper for JForm into the DSC library. Ill be on vacation for the next week just fyi.

**Comment by ChrisFrench** [comment]
Cool, have fun on vacation.

Thanks for getting to this.
